<a href="https://colab.research.google.com/github/parthsarthi1052/Data-Science/blob/main/Data6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import pandas as pd

dct={
    'name':['Tom','Nick','Krish','Jack'],
    'age':[20,21,29,18],
    'roll':[1,2,3, None]

}
# df=pd.read_csv("student_data.csv")
df=pd.DataFrame(dct,index=['a','b','c','d'])

df.fillna(0)

# df=df.dropna()
df


# df['attendance'].nunique()
# df['attendance'].value_counts()
# print(df)
# display(df)

KeyError: 'attendance'

In [ ]:
df=pd.read_csv("student_data.csv")
# display(df)

# display(df.head(3))
df.tail(3)

df.info()

df.describe()

df.columns

df.index

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

In [ ]:
df=pd.read_csv("student_data.csv")

df['attendance']
df[['internet_usage','attendance']]

df.iloc[0]
df.iloc[0:3]

df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4:8]

     study_hours  sleep_hours
30            11            5
91            11            9
98            11            6
116           11            7

In [79]:
# Ques-1
df=pd.read_csv("student_data.csv")

df.loc[df['assignments_completed']==8].iloc[0:2]

df["age"]=20

# df=df.rename(columns={'assignments_completed':'assign_completed'})
df.rename(columns={'assignments_completed':'assign_completed'},inplace= True)


df.drop("attendance",axis=1,inplace =True)
df

df.isnull()

df.notnull()

# df.agg()



# df.fillna(0,inplace=True)

,study_hours,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
9995,True,True,True,True,True,True,True,True
9996,True,True,True,True,True,True,True,True
9997,True,True,True,True,True,True,True,True
9998,True,True,True,True,True,True,True,True
9999,True,True,True,True,True,True,True,True